### ISSUE TITLE
GD-36: The action fails with Permission denied error when using an installed version

### ISSUE THREAD

**Issue by argusherd** [MikeSchulze/gdUnit4-action#36]
### The used gdUnit4-action version

gdUnit4-action@master (Pre Release/Master branch)

### The used Godot version

v4.2.stable.official.46dc27791

### Operating System

ubuntu-latest

### Describe the bug

as title

i believe this occurred because the script exited 'Install gdUnit4 plugin - ${{ inputs.version }}' step without granting executable permission to the `./addons/gdUnit4/runtest.sh` file

the action output following messages:
```bash
Run actions/github-script@v7
 Running GdUnit4 v4.2.0 tests... /home/runner/work/godot_cicd_test/godot_cicd_test/ [
  '--auto-servernum',
  './addons/gdUnit4/runtest.sh',
  '--audio-driver Dummy',
  '--display-driver x11',
  '--rendering-driver opengl3',
  '--single-window',
  '--continue',
  '--add res://tests',
  ''
] 
/usr/bin/xvfb-run: 184: ./addons/gdUnit4/runtest.sh: Permission denied
Error: The tests was failed after 0 retries with exit code: 126
```

**Comment by MikeSchulze** [comment]
Good catch, thanks for reporting
