### ISSUE TITLE
Cache rebuild fails sporadically, leading to abort

### ISSUE THREAD

**Issue by knightofiam** [MikeSchulze/gdUnit4-action#48]
### The used gdUnit4-action version

gdUnit4-action@v1

### The used Godot version

v4.3.dev6

### Operating System

ubuntu:latest

### Describe the bug

Runs fail sporadically due to cache rebuild failure; re-running multiple times eventually fixes it.
When the cache rebuild doesn't fail, the run is successful, all tests pass, and a report is generated.

Relevant log snippet:

```
Run actions/github-script@v7
Start of the recovery of the project cache ... 
ERROR: Rebuild project cache failed with exit code null. Aborting tests. 
Prepare all required actions
Getting action download info
Download action repository 'dorny/test-reporter@v1.8.0' (SHA:eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8)
Run ./.gdunit4_action/publish-test-report
Run dorny/test-reporter@v1.8.0
Check runs will be created with SHA=b5f007d99b1f59e19a294150508fb170cab816c4
Listing all files tracked by git
Found 419 files tracked by GitHub
Using test report parser 'java-junit'
Creating test report test-results-9606183511-main.xml
Error: No test report files were found
```

**Comment by knightofiam** [comment]
Please let me know if you need more information from the log, or need to see the yaml files.

**Comment by knightofiam** [comment]
It would be nice to have a yaml flag to disable caching completely, at least as a temporary workaround.

**Comment by MikeSchulze** [comment]
Have you updated the action to the latest version?
v1.1.1 is the latest version

**Comment by knightofiam** [comment]
@MikeSchulze Thanks, I’ll see if I can reproduce with v1.1.1 and report back.

**Comment by MikeSchulze** [comment]
@knightofiam any success with v1.1.1?

**Comment by knightofiam** [comment]
@MikeSchulze Seems ok so far. Wanted to wait longer in case it happens again, as it's sporadic. But I understand if you'd like to close this. Thanks for being so response, the GdUnit4 addon seems amazing so far!

**Comment by MikeSchulze** [comment]
You are free to reopen the issue if it occurs again.
Thanks for the positive feedback ;)
